// ESLint 9.x configuration (migrated from .eslintrc.json)
export default [
    {
        files: ['**/*.js'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'module',
            globals: {
                // Browser
                window: 'readonly',
                document: 'readonly',
                console: 'readonly',
                localStorage: 'readonly',
                sessionStorage: 'readonly',
                fetch: 'readonly',
                crypto: 'readonly',
                alert: 'readonly',
                confirm: 'readonly',
                setTimeout: 'readonly',
                setInterval: 'readonly',
                clearTimeout: 'readonly',
                clearInterval: 'readonly',
                URL: 'readonly',
                URLSearchParams: 'readonly',
                AbortController: 'readonly',
                btoa: 'readonly',
                atob: 'readonly',
                Blob: 'readonly',
                FormData: 'readonly',
                Headers: 'readonly',
                Request: 'readonly',
                Response: 'readonly',
                performance: 'readonly',
                IntersectionObserver: 'readonly',
                MutationObserver: 'readonly',
                Notification: 'readonly',
                FileReader: 'readonly',
                TextEncoder: 'readonly',
                TextDecoder: 'readonly',
                location: 'readonly',
                history: 'readonly',
                requestAnimationFrame: 'readonly',
                cancelAnimationFrame: 'readonly',
                navigator: 'readonly',
                Event: 'readonly',
                CustomEvent: 'readonly',
                Element: 'readonly',
                HTMLElement: 'readonly',
                Node: 'readonly',
                NodeList: 'readonly',
                getComputedStyle: 'readonly',
                scrollTo: 'readonly',
                ResizeObserver: 'readonly',

                // Node.js
                process: 'readonly',
                __dirname: 'readonly',
                __filename: 'readonly',
                require: 'readonly',
                module: 'readonly',
                exports: 'readonly',

                // Custom globals
                cryptoHelper: 'readonly',
                LazyLoader: 'readonly',
                toggleApiKey: 'readonly',
                FontAwesome: 'readonly',
                DataStore: 'readonly',
                UserModule: 'readonly',
                AppModule: 'readonly',
                IncidentModule: 'readonly',
                ChangeModule: 'readonly',
                LogModule: 'readonly',
                SettingsModule: 'readonly',
                DashboardManager: 'readonly',
                AuthModule: 'readonly',
                Security: 'readonly',
                Validator: 'readonly',
                FormValidator: 'readonly',
                CsrfProtection: 'readonly',
                RateLimiter: 'readonly',
                PasswordValidator: 'readonly',
                DateUtils: 'readonly',
                Modal: 'readonly',
                Toast: 'readonly',
                KPIWidget: 'readonly',
                QuickActions: 'readonly',
                SystemStatus: 'readonly',
                escapeHtml: 'readonly',
                sanitizeInput: 'readonly',
                showToast: 'readonly',
                openModal: 'readonly',
                closeModal: 'readonly',
                showSection: 'readonly',
                updateDashboard: 'readonly',
                initApiSync: 'readonly',
                renderAppSummary: 'readonly',
                startApplicationAfterLogin: 'readonly',
                handleLogin: 'readonly',
                handleLogout: 'readonly',
                Chart: 'readonly',
                ApiSync: 'readonly',
                refreshAllModules: 'readonly',
                Pagination: 'readonly',
                Loading: 'readonly',
                Tabs: 'readonly',
                TableSort: 'readonly',
                SearchHighlight: 'readonly',
                NotificationManager: 'readonly',
                WorkflowEngine: 'readonly',
                BackupManager: 'readonly',
                PerformanceOptimizer: 'readonly',
                StringUtils: 'readonly',
                NumberUtils: 'readonly',
                ArrayUtils: 'readonly',
            },
        },
        rules: {
            'no-unused-vars': 'warn',
            'no-console': 'off',
            'semi': ['error', 'always'],
            'quotes': ['error', 'single', { allowTemplateLiterals: true }],
            'indent': ['error', 4],
            'no-undef': 'warn',
            'eqeqeq': ['warn', 'smart'],
            'curly': ['warn', 'all'],
            'no-var': 'error',
            'prefer-const': 'warn',
        },
    },
];
