// ESLint 9.x configuration (migrated from .eslintrc.json)
export default [
    {
        files: ['**/*.js'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'module',
            globals: {
                // Browser
                window: 'readonly',
                document: 'readonly',
                console: 'readonly',
                localStorage: 'readonly',
                sessionStorage: 'readonly',
                fetch: 'readonly',
                crypto: 'readonly',
                alert: 'readonly',
                confirm: 'readonly',

                // Node.js
                process: 'readonly',
                __dirname: 'readonly',
                __filename: 'readonly',
                require: 'readonly',
                module: 'readonly',
                exports: 'readonly',

                // Custom globals
                FontAwesome: 'readonly',
                DataStore: 'readonly',
                UserModule: 'readonly',
                AppModule: 'readonly',
                IncidentModule: 'readonly',
                ChangeModule: 'readonly',
                LogModule: 'readonly',
                SettingsModule: 'readonly',
                DashboardManager: 'readonly',
                AuthModule: 'readonly',
                Security: 'readonly',
                Validator: 'readonly',
                FormValidator: 'readonly',
                CsrfProtection: 'readonly',
                RateLimiter: 'readonly',
                PasswordValidator: 'readonly',
                DateUtils: 'readonly',
                Modal: 'readonly',
                Toast: 'readonly',
                KPIWidget: 'readonly',
                QuickActions: 'readonly',
                SystemStatus: 'readonly',
                escapeHtml: 'readonly',
                sanitizeInput: 'readonly',
                showToast: 'readonly',
                openModal: 'readonly',
                closeModal: 'readonly',
                showSection: 'readonly',
                updateDashboard: 'readonly',
                initApiSync: 'readonly',
                renderAppSummary: 'readonly',
                startApplicationAfterLogin: 'readonly',
                handleLogin: 'readonly',
                handleLogout: 'readonly',
                Chart: 'readonly',
                ApiSync: 'readonly',
                refreshAllModules: 'readonly',
                Pagination: 'readonly',
                Loading: 'readonly',
                Tabs: 'readonly',
                TableSort: 'readonly',
                SearchHighlight: 'readonly',
            },
        },
        rules: {
            'no-unused-vars': 'warn',
            'no-console': 'off',
            'semi': ['error', 'always'],
            'quotes': ['error', 'single', { allowTemplateLiterals: true }],
            'indent': ['error', 4],
            'no-undef': 'warn',
            'eqeqeq': ['warn', 'smart'],
            'curly': ['warn', 'all'],
            'no-var': 'error',
            'prefer-const': 'warn',
        },
    },
];
